// @ts-nocheck
/**
 * Shared types, styles and helpers for all E-Mtaa PDF documents.
 * Layout follows Tanzanian local government document conventions:
 *   - Coat of Arms centred at top
 *   - "JAMHURI YA MUUNGANO WA TANZANIA" heading
 *   - Photo box top-left, QR code bottom-right
 *   - Application number as prominent serial ID
 *   - Dual-language (Swahili primary, English secondary)
 */
import { StyleSheet } from '@react-pdf/renderer';
import { Application } from '@/lib/supabase';
import type { UserProfile } from '@/lib/supabase';

export interface DocumentPDFProps {
  application: Application;
  lang: 'sw' | 'en';
  qrDataUrl?: string;   // pre-generated by useQRCode hook; falls back to API URL
}

// ─── Colour tokens ─────────────────────────────────────────────────────────────
const C = {
  ink:        '#0f0f0f',
  inkLight:   '#44403c',
  inkFaint:   '#78716c',
  rule:       '#d6d3d1',
  ruleLight:  '#f0eeec',
  emerald:    '#065f46',
  emeraldMid: '#059669',
  emeraldBg:  '#f0fdf4',
  gold:       '#92400e',
  goldBg:     '#fef9ee',
  white:      '#ffffff',
  pageBg:     '#fafaf8',
};

// ─── Shared stylesheet ─────────────────────────────────────────────────────────
export const commonStyles = StyleSheet.create({

  // Page
  page: {
    paddingTop: 36,
    paddingBottom: 60,
    paddingHorizontal: 44,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: C.ink,
    backgroundColor: C.pageBg,
  },

  // ── Watermark ──────────────────────────────────────────────────────────────
  watermark: {
    position: 'absolute',
    top: '38%',
    left: '15%',
    fontSize: 96,
    color: C.ruleLight,
    opacity: 0.6,
    transform: 'rotate(-40deg)',
  },

  // ── Photo box (top-left absolute) ─────────────────────────────────────────
  photoSection: {
    position: 'absolute',
    top: 36,
    left: 44,
    width: 76,
    alignItems: 'center',
  },
  photoBox: {
    width: 68,
    height: 82,
    borderWidth: 1.5,
    borderColor: C.inkFaint,
    backgroundColor: C.ruleLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 3,
  },
  photo: {
    width: 66,
    height: 80,
    objectFit: 'cover',
  },
  photoPlaceholder: {
    fontSize: 7,
    color: C.inkFaint,
    textAlign: 'center',
    lineHeight: 1.4,
  },
  nidaLabel: {
    fontSize: 5.5,
    color: C.inkFaint,
    marginBottom: 1,
    textAlign: 'center',
  },
  nidaNumber: {
    fontSize: 6.5,
    fontWeight: 'bold',
    color: C.ink,
    textAlign: 'center',
    fontFamily: 'Courier',
  },

  // ── Government header (centred) ────────────────────────────────────────────
  header: {
    alignItems: 'center',
    marginBottom: 6,
    paddingLeft: 80,   // clear the photo box
  },
  logo: {
    width: 54,
    height: 54,
    marginBottom: 6,
  },
  country: {
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
    textAlign: 'center',
    marginBottom: 1,
  },
  office: {
    fontSize: 9,
    fontWeight: 'bold',
    color: C.inkLight,
    textAlign: 'center',
    marginBottom: 2,
  },
  council: {
    fontSize: 8.5,
    color: C.inkLight,
    textAlign: 'center',
    marginBottom: 6,
  },
  divider: {
    width: 56,
    height: 2,
    backgroundColor: C.emerald,
    marginTop: 4,
  },

  // ── Document title ─────────────────────────────────────────────────────────
  titleBlock: {
    marginTop: 14,
    marginBottom: 4,
    alignItems: 'center',
  },
  title: {
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center',
    textDecoration: 'underline',
    textTransform: 'uppercase',
    color: C.emerald,
    letterSpacing: 1,
  },
  appNumberBadge: {
    marginTop: 6,
    backgroundColor: C.emerald,
    paddingVertical: 3,
    paddingHorizontal: 14,
    alignSelf: 'center',
  },
  appNumberText: {
    color: C.white,
    fontSize: 9,
    fontFamily: 'Courier',
    fontWeight: 'bold',
    letterSpacing: 1,
  },

  // ── Section headers ────────────────────────────────────────────────────────
  sectionHeader: {
    backgroundColor: C.emeraldBg,
    paddingVertical: 5,
    paddingHorizontal: 8,
    marginBottom: 8,
    marginTop: 14,
    borderLeftWidth: 3,
    borderLeftColor: C.emeraldMid,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 8.5,
    fontWeight: 'bold',
    color: C.emerald,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  // ── Info rows ──────────────────────────────────────────────────────────────
  infoRow: {
    flexDirection: 'row',
    marginBottom: 6,
    paddingBottom: 5,
    borderBottomWidth: 0.5,
    borderBottomColor: C.ruleLight,
    minHeight: 16,
  },
  infoLabel: {
    width: '38%',
    fontSize: 9,
    fontWeight: 'bold',
    color: C.inkLight,
    paddingRight: 6,
  },
  infoValue: {
    width: '62%',
    fontSize: 9.5,
    color: C.ink,
    fontWeight: 'bold',
  },

  // ── Two-column layout ──────────────────────────────────────────────────────
  twoCol: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  colLeft: { width: '48%' },
  colRight: { width: '48%' },

  // ── Signature section ──────────────────────────────────────────────────────
  signatureSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 30,
    marginBottom: 8,
  },
  signatureBox: {
    width: '44%',
    alignItems: 'center',
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: C.inkFaint,
    marginBottom: 6,
    width: '100%',
  },
  signatureName: {
    fontSize: 9,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    textAlign: 'center',
    marginBottom: 2,
  },
  signatureTitle: {
    fontSize: 8,
    color: C.inkFaint,
    textAlign: 'center',
  },
  stampBox: {
    width: 64,
    height: 64,
    borderWidth: 1,
    borderColor: C.rule,
    borderRadius: 32,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  stampText: {
    fontSize: 6,
    color: C.rule,
    textAlign: 'center',
  },

  // ── QR code block (bottom-right absolute) ─────────────────────────────────
  qrSection: {
    position: 'absolute',
    bottom: 62,
    right: 44,
    alignItems: 'center',
    width: 76,
  },
  qrBorder: {
    borderWidth: 1,
    borderColor: C.rule,
    padding: 3,
    backgroundColor: C.white,
    marginBottom: 3,
  },
  qrCode: {
    width: 64,
    height: 64,
  },
  qrLabel: {
    fontSize: 5.5,
    color: C.inkFaint,
    textAlign: 'center',
    lineHeight: 1.4,
  },
  qrRef: {
    fontSize: 5,
    color: C.inkFaint,
    textAlign: 'center',
    fontFamily: 'Courier',
    marginTop: 1,
  },

  // ── Footer ─────────────────────────────────────────────────────────────────
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 44,
    right: 44,
    borderTopWidth: 0.5,
    borderTopColor: C.rule,
    paddingTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 7,
    color: C.inkFaint,
    fontStyle: 'italic',
    flex: 1,
  },
  metadata: {
    fontSize: 5.5,
    color: C.rule,
    fontFamily: 'Courier',
    textAlign: 'right',
  },

  // ── Notice / info box ──────────────────────────────────────────────────────
  noticeBox: {
    backgroundColor: C.goldBg,
    borderLeftWidth: 3,
    borderLeftColor: C.gold,
    padding: 10,
    marginVertical: 10,
  },
  noticeText: {
    fontSize: 8.5,
    color: C.gold,
    lineHeight: 1.5,
  },

  // ── Subject line (for letter-format docs) ─────────────────────────────────
  subject: {
    fontSize: 10,
    fontWeight: 'bold',
    marginBottom: 10,
    textDecoration: 'underline',
  },
  body: {
    fontSize: 9.5,
    lineHeight: 1.7,
    textAlign: 'justify',
    marginBottom: 14,
    color: C.ink,
  },
});

// ─── Helpers ───────────────────────────────────────────────────────────────────

/** Generate the QR code image URL (external API fallback used by default).
 *  For async pre-generation use generateQRDataUrl from src/lib/qr.ts.
 */
export const generateQRCodeUrl = (application: Application, serviceCode: string): string => {
  const payload = JSON.stringify({
    ref: application.application_number ?? '',
    id:  application.id,
    svc: serviceCode,
    dt:  new Date().toISOString().split('T')[0],
  });
  return `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(payload)}`;
};

export const formatFullName = (
  user: Pick<UserProfile, 'first_name' | 'middle_name' | 'last_name'> | null | undefined
): string => {
  if (!user) return 'N/A';
  return `${user.first_name ?? ''} ${user.middle_name ?? ''} ${user.last_name ?? ''}`
    .replace(/\s+/g, ' ').trim() || 'N/A';
};

export const formatDate = (dateString?: string | null): string => {
  if (!dateString) return new Date().toLocaleDateString('sw-TZ');
  try { return new Date(dateString).toLocaleDateString('sw-TZ'); }
  catch { return dateString; }
};

export const formatCurrency = (amount?: number | null): string => {
  if (!amount && amount !== 0) return 'N/A';
  return `TZS ${Number(amount).toLocaleString('en-TZ')}`;
};

/** Shared government header used by every document type. */
export { commonStyles as default };
